DROP TABLE IF EXISTS hits;
drop table if exists users cascade;
drop table if exists categories cascade;
drop table if exists locations cascade;
drop table if exists events cascade;
drop table if exists compilations cascade;
drop table if exists compilations_events cascade;
drop table if exists comments cascade;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255)                NOT NULL,
    uri       VARCHAR(255)                NOT NULL,
    ip        VARCHAR(45)                NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);